### PR TITLE
Feat | Advanced Filter + Redesign

### PR DESCRIPTION
**Pull request by edwinmp**

### CODE REVIEW

**Comment by edwinmp** [comment]
@akmiller01 this is ready for testing. Don't want to get into the e2e tests until the changes are signed off.

**Comment by akmiller01** [comment]
Cheers @edwinmp , taking a look now. Let me know if you need help refactoring the Cypress tests later.

**Comment by akmiller01** [comment]
Some quick observations:

First, I think we need to consider the relationship between the simple search bar and the advanced search bar. Intuitively, these are the steps I take:

1. Type a query into the box, e.g. `oregano`, click `Search`, see results.
2. Wanting to filter the results down further, click `Advanced`, add a rule, click run.
3. See results are no longer related to the original query in the box.

image

So maybe it makes sense that if a user has a query in the box, and then clicks advance, to automatically populate a rule with All narratives equal to their search term? And then maybe once a user adds additional filters to an advanced query and clicks "run" the original searchbox changes somehow to indicate that the results are being driven by the advanced filters instead of the search box, and running another query from the search box will clear the advanced filters. Maybe something like `Results filtered by Advanced parameters. See Advanced tab for more details`

The same issue works in reverse, if you first run an Advanced query, and then type something in the box, you might think they're additive in some way, but the Simple query overrides the Advanced query while the Advanced query stays populated in the modal.

And if you run an advanced query without first running a simple query (especially one that fails to produce results), you get a rather blank page that can be difficult to tell what's going on:

image


Second, default date fields to a date. I think they're defaulting null and that's causing a weird glitch where it appears to have a value but fails to validate:

image

Third, changing a rule field tries to copy the value across; even if the data types don't line up. For e.g. if you select xml lang == aa, and then change to a generated datetime, it will try to put `aa` in the datetime field.

Fourth, clicking outside of a dropdown or modal should close it. If you first click "Download" and then click "Advanced" it doesn't close the "Download" dropdown, and renders it on top of the Advanced modal: 
image

Fifth, I like the q= in the URL for simple searches. I think we could probably just take the entirety of the query param given to Datastore Services API and put it as q= in the URL as well, and make that a sharable URL in place of the import/export. It would just then be a matter of the system picking up the q= param and re-populating the search box.

Cheers,
-Alex

**Comment by edwinmp** [comment]
Thanks for the feedback @akmiller01 ... Thinking of adding a `Clear/Reset` button as well, for when the filter size grows too large.

**Comment by akmiller01** [comment]
A Clear button sounds like a good idea, as long as it's not too easy to accidentally clear. Maybe a "Are you sure?" confirmation after clicking Clear.

**Comment by edwinmp** [comment]
@akmiller01 have another click through and let me know if I've missed something.

**Comment by akmiller01** [comment]
@edwinmp that all looks good from every click I can try. I think the next step will be to rewrite the e2e so it can do a comprehensive test of every field type, plus an export and reimport programmatically!

**Comment by akmiller01** [comment]
Excellent! All looks good. Shall we get it up on dev and test it out a bit further from there?

**Review by akmiller01 — APPROVED** [review]

**Pull request merged**
